# Generated by Django 4.1 on 2022-08-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prducto', models.TextField()),
                ('precio', models.IntegerField()),
                ('fecha_encargo', models.DateField()),
                ('fecha_carga', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Refaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('modelo', models.TextField()),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.TextField()),
                ('precio', models.TextField()),
                ('total', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
