# Generated by Django 4.1 on 2022-09-07 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('refac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refaccion',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refaccion',
            name='descripcion',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='refaccion',
            name='editado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refaccion',
            name='modelo',
            field=models.TextField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='refaccion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='refaccion',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
